cjoxmake: main.c memory.c chunk.h chunk.c common.h memory.h debug.h debug.c value.h value.c vm.h vm.c compiler.h compiler.c scanner.h scanner.c
	gcc -o main main.c memory.c chunk.c debug.c value.c vm.c scanner.c compiler.c -I.
