cjoxmake: main.c memory.c chunk.h chunk.c common.h memory.h debug.h debug.c value.h value.c vm.h vm.c object.h object.c compiler.h compiler.c scanner.h scanner.c table.h table.c
	gcc -o main main.c memory.c chunk.c debug.c value.c vm.c scanner.c compiler.c object.c table.c -I.
